### ISSUE TITLE
Compilation failed for src/tmb/stateSpace.cpp

### ISSUE THREAD

**Issue by Bai-Li-NOAA** [Andrea-Havron-NOAA/FIMS-software#6]
I am trying to compile the stateSpace.cpp using the code below but the compilations failed. 
```r
TMB::compile("~/Desktop/FIMS-software/src/tmb/stateSpace.cpp")
```

The error message:
`stateSpace.cpp:52:36: error: 'hyperpars_sd' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]`

Please let me know if I need to modify the R code and add flags to compile the code. Thanks!

**Comment by Andrea-Havron-NOAA** [comment]
fixed bug that was causing this issue
